### ISSUE TITLE
Error enabling nameless.dll

### ISSUE THREAD

**Issue by dickyo098** [dove-zp/ce.plugin.nameless#1]
how to fix when im adding pluggin in cheat engine

**Comment by dove-zp** [comment]
I would assume that is a redistributable error being thrown on when running the plugin with Cheat Engine. I didn't release the v1.0.0 build with embedded Microsoft Runtime Libraries when I compiled. I'll try to reduce the dependencies in following releases. 
![depends_PMfaUQSimz](https://user-images.githubusercontent.com/89095890/165391881-1476e870-5ff4-40ad-a5b5-83c4f64b2b42.png)
Until then, you'll have to install these redistributables yourself. 
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Feel free to open this issue again and provide a screenshot of the error if it still remains a problem.
